apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: jj7pncmy9-go 
  janus-idp.io/tekton: jj7pncmy9-go
  backstage.io/kubernetes-id: jj7pncmy9-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jj7pncmy9-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml